version: '3'

services:
  bqp-content-mgmt-service:
    image: bqp-content-mgmt-service
    container_name: bqp-content-mgmt-service
    build:
      context: ./
      dockerfile: ./compose/local/Dockerfile
    command: /start
    env_file:
      - src/config/.env
    expose:
      - 6002
    volumes:
      - .:/app:z
    ports:
      - 6002:6002


networks:
  default:
    external:
      name: bqp_network